version: '3.9'

services:
  django_gunicorn:
    volumes:
      - static:/static
    build: 
      context: .
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "8080:80"
    depends_on:
      - django_gunicorn

  # djangoapp:
  #   container_name: djangoapp
  #   build: .
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     - PG_USER=athish
  #     - PG_PASSWORD=Athish@123
  #     - PG_DB=myproject
  #     - PG_HOST=db
  #     - PG_PORT=5432
  #   depends_on:
  #     - db

  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=dryz
    ports:
      - "5433:5432"
  
volumes:
  static: {}  # Corrected volume declaration
  # pgdata: {}
