version: '3.9'

services:
  django_gunicorn:
    volumes:
      - static:/static
    build: 
      context: .
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/static
    ports:
      - "8080:80"
    # depends_on:
    #   - django_gunicorn
    networks:
      - mynetwork
    # Add health check or wait-for logic here to ensure Django is ready

  # Uncomment the following section if you plan to use the djangoapp service
  # djangoapp:
  #   container_name: djangoapp
  #   build: .
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     - PG_USER=athish
  #     - PG_PASSWORD=Athish@123
  #     - PG_DB=myproject
  #     - PG_HOST=db
  #     - PG_PORT=5432
  #   depends_on:
  #     - db

  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=athish
      - POSTGRES_PASSWORD=Athish@123
      - POSTGRES_DB=dryzz
    ports:
      - "5433:5432"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
  
volumes:
  static: {}
